# Base Configuration - Shared Defaults
# This file contains default settings used across all environments

# System Configuration
system:
  name: "RAG System"
  version: "2.0.0"
  debug: false
  max_workers: 4
  timeout: 30
  cache_enabled: true
  cache_ttl: 3600

# Text Processing Configuration
text_splitter:
  type: "semantic"  # Options: fixed_size, semantic, sliding, sentence
  chunk_size: 512
  chunk_overlap: 128
  min_chunk_size: 100
  max_chunk_size: 1000
  respect_sentences: true
  respect_paragraphs: true

# Embedding Configuration
embedder:
  type: "sentence_transformer"
  model_name: "all-MiniLM-L6-v2"
  cache_dir: "./embedding_cache"
  dimension: 384
  batch_size: 32
  normalize: true
  cache_embeddings: true

# Vector Store Configuration
vector_store:
  type: "chromadb"  # Options: chromadb, faiss, hybrid
  path: "./chroma_db"
  collection_name: "rag_collection"
  distance_metric: "cosine"
  index_type: "HNSW"
  ef_construction: 200
  ef_search: 50

# Generation Configuration
generator:
  type: "ollama"  # Options: ollama, openai, anthropic, huggingface
  model_name: "gemma:2b"
  temperature: 0.7
  max_tokens: 512
  top_p: 0.9
  frequency_penalty: 0.0
  presence_penalty: 0.0
  stop_sequences: ["\n\n"]
  host: "localhost"
  port: 11434

# Retrieval Configuration
retrieval:
  strategy: "hybrid"  # Options: dense, sparse, hybrid, adaptive
  k_documents: 10
  rerank: true
  reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  rerank_top_k: 5
  use_mmr: true
  mmr_lambda: 0.5
  hybrid_alpha: 0.5
  similarity_threshold: 0.7

# Reranker Configuration
reranker:
  type: "cross_encoder"
  model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  batch_size: 16
  max_length: 512

# Context Management
context:
  max_context_length: 2048
  compression_enabled: false
  compression_ratio: 0.5
  summarization_enabled: false
  context_ordering: "relevance"  # Options: relevance, diversity, recency

# Conversation Configuration
conversation:
  memory_enabled: true
  memory_type: "buffer"  # Options: buffer, summary, knowledge_graph
  max_history: 10
  max_turns: 10
  max_tokens: 2000
  summarize_after: 5
  context_window: 3

# Query Optimization
query_optimization:
  enabled: true
  rewrite: true
  expand: true
  decompose: true
  use_hyde: false
  max_expansion: 3
  complexity_threshold: 0.5

# Performance Configuration
performance:
  batch_processing: true
  batch_size: 32
  timeout_seconds: 30
  parallel_processing: true
  max_workers: 4
  use_gpu: false
  gpu_device_id: 0
  memory_fraction: 0.8

# Cache Configuration
cache:
  embedding_cache: true
  query_cache: true
  response_cache: false
  cache_backend: "in_memory"  # Options: redis, memcached, in_memory
  ttl_seconds: 3600
  max_size: 1000

# Security Configuration (Base defaults)
security:
  input_validation: true
  max_input_length: 1000
  max_query_length: 1000
  max_document_size: 10485760  # 10MB
  sanitize_outputs: true
  block_harmful_content: true
  audit_logging: false

# Rate Limiting (Base defaults)
rate_limiting:
  enabled: false
  requests_per_minute: 60
  requests_per_hour: 1000
  burst_size: 10
  strategy: "sliding_window"

# API Configuration (Base defaults)
api:
  host: "localhost"
  port: 8000
  base_path: "/api"
  version: "v1"
  workers: 4
  timeout: 30
  cors_enabled: true

# CORS Configuration
cors:
  enabled: true
  allowed_origins: ["http://localhost:3000", "http://localhost:5173", "http://localhost:8501"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE"]
  allowed_headers: ["Content-Type", "Authorization", "X-API-Key"]
  expose_headers: ["X-Request-ID"]
  allow_credentials: true
  max_age: 600

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  file_enabled: false
  console_enabled: true
  max_file_size: 104857600  # 100MB
  backup_count: 5

# Monitoring Configuration (Base defaults)
monitoring:
  enabled: false
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  performance_tracking: false
  log_level: "INFO"

# Evaluation Configuration
evaluation:
  enabled: false
  ragas_enabled: false
  ragas_metrics:
    - "faithfulness"
    - "answer_relevancy"
    - "context_relevancy"
    - "context_precision"
  min_score_threshold: 0.6
  log_evaluations: false
  auto_evaluate: false
  evaluation_interval: 10

# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 1
  fallback_to_simple: true
  log_errors: true
  alert_on_failure: false

# Storage Configuration
storage:
  base_path: "./rag_storage"
  backup_enabled: false
  backup_interval_hours: 24
  backup_retention_days: 7

# Feature Flags
features:
  streaming_responses: false
  multi_language_support: false
  voice_input: false
  export_conversations: false
  collaborative_filtering: false
  active_learning: false
  federated_search: false
  knowledge_graph_enabled: false
  ab_testing_enabled: false

# Knowledge Graph (Base defaults)
knowledge_graph:
  enabled: false
  max_entities_per_doc: 50
  max_relations_per_doc: 100
  max_hops: 2
  max_nodes_per_query: 20

# A/B Testing (Base defaults)
ab_testing:
  enabled: false
  default_allocation: "random"
  significance_level: 0.05
  minimum_sample_size: 100

# Document Processing
document_processing:
  supported_formats: [".txt", ".pdf", ".doc", ".docx", ".md", ".json"]
  max_file_size: 10485760  # 10MB
  ocr_enabled: false
  preserve_structure: true