apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-backend-config
  namespace: rag-system
  labels:
    app.kubernetes.io/name: rag-backend
    app.kubernetes.io/component: configmap
data:
  # Application configuration
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  
  # API Configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_WORKERS: "4"
  
  # Vector Database
  CHROMA_HOST: "chromadb-service"
  CHROMA_PORT: "8000"
  
  # Embedding Configuration
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  EMBEDDING_CACHE_SIZE: "1000"
  
  # RAG Configuration
  MAX_CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"
  TOP_K_RETRIEVAL: "5"
  
  # Performance Settings
  MAX_CONCURRENT_REQUESTS: "100"
  REQUEST_TIMEOUT: "30"
  
  # Health Check
  HEALTH_CHECK_INTERVAL: "30"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-frontend-config
  namespace: rag-system
  labels:
    app.kubernetes.io/name: rag-frontend
    app.kubernetes.io/component: configmap
data:
  # Frontend configuration
  VITE_API_BASE_URL: "http://rag-backend-service:8000"
  VITE_APP_TITLE: "RAG System"
  VITE_APP_VERSION: "1.0.0"
  VITE_ENVIRONMENT: "production"