apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-backend-config
  namespace: rag-staging
data:
  # Staging-specific configuration (production-like settings)
  APP_ENV: "staging"
  LOG_LEVEL: "INFO"
  
  # API Configuration for staging
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_WORKERS: "3"
  
  # Vector Database
  CHROMA_HOST: "chromadb-service"
  CHROMA_PORT: "8000"
  
  # Embedding Configuration
  EMBEDDING_MODEL: "sentence-transformers/all-MiniLM-L6-v2"
  EMBEDDING_CACHE_SIZE: "800"
  
  # RAG Configuration
  MAX_CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"
  TOP_K_RETRIEVAL: "5"
  
  # Performance Settings
  MAX_CONCURRENT_REQUESTS: "80"
  REQUEST_TIMEOUT: "30"
  
  # Staging features
  ENABLE_DEBUG_ENDPOINTS: "false"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "true"
  
  # Security settings (staging-appropriate)
  ENABLE_CORS: "true"
  CORS_ORIGINS: "https://rag-staging.your-domain.com"
  
  # Health Check
  HEALTH_CHECK_INTERVAL: "30"
  
  # Blue-Green deployment settings
  DEPLOYMENT_COLOR: "COLOR_LABEL"
  CANARY_ENABLED: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-frontend-config
  namespace: rag-staging
data:
  # Frontend staging configuration
  VITE_API_BASE_URL: "https://api-staging.rag.your-domain.com"
  VITE_APP_TITLE: "RAG System (Staging)"
  VITE_APP_VERSION: "1.0.0-staging"
  VITE_ENVIRONMENT: "staging"
  VITE_DEBUG_MODE: "false"
  VITE_LOG_LEVEL: "info"
  VITE_ENABLE_ANALYTICS: "false"  # No analytics in staging
  VITE_SENTRY_ENABLED: "true"     # Error tracking in staging